---
- name: "Instalando dependencias bÃ¡sicas"
  apt:
    pkg: "{{ runtime_base_dependencies }}"
    state: present
    update_cache: yes

- include_tasks: "docker.yml"
  when: runtime_install_docker
- include_tasks: "bridge.yml"
  when: runtime_enable_bridge_network
